### ISSUE TITLE
F6 - Populate README.md file

### ISSUE THREAD

**Issue by BoskoNikolic** [BoskoNikolic/endavaTraining#11]
This file should contain the description, what is the purpose
of this project, describe its contents and how to run it.

e.g. of possible sections

project name

This test framework contains tests written for XYZ website (https://.....) :

Pre-requisites

list of Pre-requisites
Running Tests

list steps required to run test starting with repository clone
Browser choices

list supported browsers and how to add them

**Comment by JovanPEndava** [comment]
Issue resolved.
